# Build a baseline Ubuntu distro that supports UTF-8
FROM ubuntu:18.04 as baseline
RUN apt-get clean && apt-get update \
    && apt-get install -y --no-install-recommends locales \
    && locale-gen en_US.UTF-8 
RUN apt-get install -y mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file sudo > nul

# Build the neologism dictionary
FROM baseline as build-mecab-ipadic-neologd
ADD . /app
RUN echo yes | /app/bin/install-mecab-ipadic-neologd -n -u
#RUN echo Done installing install-mecab-ipadic-neologd
#RUN apt-get remove --purge -y libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file
#RUN apt-get clean
#RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN echo "8月3日に放送された「中居正広の金曜日のスマイルたちへ」(TBS系)で、1日たった5分でぽっこりおなかを解消するというダイエット方法を紹介。キンタロー。 のダイエットにも密着。" | mecab -d /usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd/

# Create a tiny distro with just the build dictionary
FROM alpine as mecab-ipadic-neologd
WORKDIR mecab-ipadic-neologd
ADD build-mecab-ipadic-neologd:/usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd .
